fix: have generateURL return null for undefined filenames
payloadcms/plugin-cloud-storage pull request #13
Opened 2022-09-21 01:11 UTC by KGZM

This lets the afterRead hook skip URLs for non-existent image sizes, cleaning up the following error:
```

[00:47:11] ERROR (payload): TypeError: The "path" argument must be of type string. Received undefined
    at new NodeError (node:internal/errors:387:5)
    at validateString (node:internal/validators:116:11)
    at Object.join (node:path:1172:7)
    at Object.generateURL (/project/node_modules/@payloadcms/plugin-cloud-storage/src/adapters/s3/generateURL.ts:13:48)
    at /project/node_modules/@payloadcms/plugin-cloud-storage/src/hooks/afterRead.ts:17:31
    at step (/project/node_modules/@payloadcms/plugin-cloud-storage/dist/hooks/afterRead.js:33:23)
    at Object.next (/project/node_modules/@payloadcms/plugin-cloud-storage/dist/hooks/afterRead.js:14:53)
    at /project/node_modules/@payloadcms/plugin-cloud-storage/dist/hooks/afterRead.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/project/node_modules/@payloadcms/plugin-cloud-storage/dist/hooks/afterRead.js:4:12)
```

I believe this was intended, based on `||` being used on the return value of generateURL here: https://github.com/payloadcms/plugin-cloud-storage/blob/2cd83f2aa6ceea00381dbf5ca16e1c83deb9f4f0/src/hooks/afterRead.ts#L23

2022-09-22 18:55 UTC, vedransisic commented
Can someone please accept this in!
I need this fixed as well.

2022-09-23 14:00 UTC, afzaalahmad requested changes
It is good if you'll change it all usages of filename to exit first if there is no filename.

2022-09-23 14:00 UTC, afzaalahmad commented on src/adapters/azure/generateURL.ts
> +    if (filename) {
It is good strategy to exit first.
It would be better if you change it to this:
```
If (!filename) return null
```

2022-09-23 16:29 UTC, jmikrut commented
Hey @KGZM — thank you for the PR! 

We dug into this and figured out the best way to handle the changes would be to just simply only run the `adapter.generateURL` _**if the filename is set**_. That way, the plugin is handling the logic, and not the adapters themselves.

Check it out here: 
84cd214a89c32598969eb76aec9f22c1b18a62b1

I'm going to close this one in favor of the commit we pushed but really thank you for jumping in here!

2022-09-23 16:29 UTC, closed without merging

2022-09-23 17:01 UTC, vedransisic commented
@jmikrut Thanks for the quick fix. That solves it! Really thankful for this plugin itself.